apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: frontend
    count: 1
  - name: catalogue
    count: 1
  - name: voting
    count: 1
  - name: recommendation
    count: 1

images:
  - name: craftista-frontend
    newName: REPLACE_WITH_ECR_REPO_URL/craftista-frontend
    newTag: latest
  - name: craftista-catalogue
    newName: REPLACE_WITH_ECR_REPO_URL/craftista-catalogue
    newTag: latest
  - name: craftista-voting
    newName: REPLACE_WITH_ECR_REPO_URL/craftista-voting
    newTag: latest
  - name: craftista-recommendation
    newName: REPLACE_WITH_ECR_REPO_URL/craftista-recommendation
    newTag: latest
